SCAM=scam   # fill in your absolute path

testall: test1 test2 \
	test3 \
	test4 \
	test5 \
	test6 \
	test7 \
	test8 \
	test9 \
	test10 \
	test12 \
	test13 \
	test14 \
	test15 \
	test16 \
	test17 \
	test18 \
	test19 \
	test20 \
	test21 \
	test23 \
	test24 \
	test25 \
	test26 \
	test27 \
	test28 \
	test29 \
	test30 \
	test31 \
	test32 \
	test34 \
	test35 \
	test36 \
	test37 \
	test38 \
	test39 \
	test45 \
	test46 \
	test47 \
	test48 \
	test49 \
	test50 \
	test51 \
	test52 \
	test56 \
	test57 \
	test58 \
	test59 \
	test60 \
	test61 \
	test62 \
	test63 \
	test64 \
	test65 \
	test67 \
	test68 \
	test69 \
	test70 \
	test71 \
	test72 \
	test73 \
	test74 \
	test75 \
	test76 \
	test78 \
	test80 \
	test81 \
	test82 \
	test83 \
	test84 \
	test85 \
	test86 \
	test87 \
	test88 \
	test89 \
	test90 \
	test91 \
	test92 \
	test93 \


test1: task1.scm testcase/task1.0
	@echo "TEST #1"
	$(SCAM) -r task1.scm testcase/task1.0 > result
	diff result testcase/task1.0.expected
	@echo ""

test2: task1.scm testcase/task1.1
	@echo "TEST #2"
	$(SCAM) -r task1.scm testcase/task1.1 >result
	diff result testcase/task1.1.expected
	@echo ""

test3: task1.scm testcase/task1.2
	@echo "TEST #3"
	$(SCAM) -r task1.scm testcase/task1.2 > result
	diff result testcase/task1.2.expected
	@echo ""

test4: task1.scm testcase/task1.3
	@echo "TEST #4"
	$(SCAM) -r task1.scm testcase/task1.3 > result
	diff result testcase/task1.3.expected
	@echo ""

test5: task1.scm testcase/task1.4
	@echo "TEST #5"
	$(SCAM) -r task1.scm testcase/task1.4 > result
	diff result testcase/task1.4.expected
	@echo ""

test6: task1.scm testcase/task1.5
	@echo "TEST #6"
	$(SCAM) -r task1.scm testcase/task1.5 > result
	diff result testcase/task1.5.expected
	@echo ""

test7: task1.scm testcase/task1.6
	@echo "TEST #7"
	$(SCAM) -r task1.scm testcase/task1.6 > result
	diff result testcase/task1.6.expected
	@echo ""

test8: task1.scm testcase/task1.7
	@echo "TEST #8"
	$(SCAM) -r task1.scm testcase/task1.7 >result
	diff result testcase/task1.7.expected
	@echo ""

test9: task1.scm testcase/task1.8
	@echo "TEST #9"
	$(SCAM) -r task1.scm testcase/task1.8 > result
	diff result testcase/task1.8.expected
	@echo ""

test10: task1.scm testcase/task1.9
	@echo "TEST #10"
	$(SCAM) -r task1.scm testcase/task1.9 > result
	diff result testcase/task1.9.expected
	@echo ""

#test11: task1.scm testcase/task1.10
#	@echo "TEST #11"
#	$(SCAM) -r task1.scm testcase/task1.10 > result
#	diff result testcase/task1.10.expected
#	@echo ""

test12: task2.scm testcase/task2.0
	@echo "TEST #12"
	$(SCAM) -r task2.scm testcase/task2.0 > result
	diff result testcase/task2.0.expected
	@echo ""

test13: task2.scm testcase/task2.1
	@echo "TEST #13"
	$(SCAM) -r task2.scm testcase/task2.1 > result
	diff result testcase/task2.1.expected
	@echo ""

test14: task2.scm testcase/task2.2
	@echo "TEST #14"
	$(SCAM) -r task2.scm testcase/task2.2 > result
	diff result testcase/task2.2.expected
	@echo ""

test15: task2.scm testcase/task2.3
	@echo "TEST #15"
	$(SCAM) -r task2.scm testcase/task2.3 > result
	diff result testcase/task2.3.expected
	@echo ""

test16: task2.scm testcase/task2.4
	@echo "TEST #16"
	$(SCAM) -r task2.scm testcase/task2.4 > result
	diff result testcase/task2.4.expected
	@echo ""

test17: task2.scm testcase/task2.5
	@echo "TEST #17"
	$(SCAM) -r task2.scm testcase/task2.5 > result
	diff result testcase/task2.5.expected
	@echo ""

test18: task2.scm testcase/task2.6
	@echo "TEST #18"
	$(SCAM) -r task2.scm testcase/task2.6 > result
	diff result testcase/task2.6.expected
	@echo ""

test19: task2.scm testcase/task2.7
	@echo "TEST #19"
	$(SCAM) -r task2.scm testcase/task2.7 > result
	diff result testcase/task2.7.expected
	@echo ""

test20: task2.scm testcase/task2.8
	@echo "TEST #20"
	$(SCAM) -r task2.scm testcase/task2.8 > result
	diff result testcase/task2.8.expected
	@echo ""

test21: task2.scm testcase/task2.9
	@echo "TEST #21"
	$(SCAM) -r task2.scm testcase/task2.9 > result
	diff result testcase/task2.9.expected
	@echo ""

#test22: task2.scm testcase/task2.10
#	@echo "TEST #22"
#	$(SCAM) -r task2.scm testcase/task2.10 > result
#	diff result testcase/task2.10.expected
#	@echo ""

test23: task3.scm testcase/task3.0
	@echo "TEST #23"
	$(SCAM) -r task3.scm testcase/task3.0 > result
	diff result testcase/task3.0.expected
	@echo ""

test24: task3.scm testcase/task3.1
	@echo "TEST #24"
	$(SCAM) -r task3.scm testcase/task3.1 > result
	diff result testcase/task3.1.expected
	@echo ""

test25: task3.scm testcase/task3.2
	@echo "TEST #25"
	$(SCAM) -r task3.scm testcase/task3.2 > result
	diff result testcase/task3.2.expected
	@echo ""

test26: task3.scm testcase/task3.3
	@echo "TEST #26"
	$(SCAM) -r task3.scm testcase/task3.3 > result
	diff result testcase/task3.3.expected
	@echo ""

test27: task3.scm testcase/task3.4
	@echo "TEST #27"
	$(SCAM) -r task3.scm testcase/task3.4 > result
	diff result testcase/task3.4.expected
	@echo ""

test28: task3.scm testcase/task3.5
	@echo "TEST #28"
	$(SCAM) -r task3.scm testcase/task3.5 > result
	diff result testcase/task3.5.expected
	@echo ""

test29: task3.scm testcase/task3.6
	@echo "TEST #29"
	$(SCAM) -r task3.scm testcase/task3.6 > result
	diff result testcase/task3.6.expected
	@echo ""

test30: task3.scm testcase/task3.7
	@echo "TEST #30"
	$(SCAM) -r task3.scm testcase/task3.7 > result
	diff result testcase/task3.7.expected
	@echo ""

test31: task3.scm testcase/task3.8
	@echo "TEST #31"
	$(SCAM) -r task3.scm testcase/task3.8 > result
	diff result testcase/task3.8.expected
	@echo ""

test32: task3.scm testcase/task3.9
	@echo "TEST #32"
	$(SCAM) -r task3.scm testcase/task3.9 > result
	diff result testcase/task3.9.expected
	@echo ""

#test33: task3.scm testcase/task3.10
#	@echo "TEST #33"
#	$(SCAM) -r task3.scm testcase/task3.10 > result
#	diff result testcase/task3.10.expected
#	@echo ""

test34: task4.scm testcase/task4.0
	@echo "TEST #34"
	$(SCAM) -r task4.scm testcase/task4.0 > result
	diff result testcase/task4.0.expected
	@echo ""

test35: task4.scm testcase/task4.1
	@echo "TEST #35"
	$(SCAM) -r task4.scm testcase/task4.1 > result 
	diff result testcase/task4.1.expected
	@echo ""

test36: task4.scm testcase/task4.2
	@echo "TEST #36"
	$(SCAM) -r task4.scm testcase/task4.2 > result
	diff result testcase/task4.2.expected
	@echo ""

test37: task4.scm testcase/task4.3
	@echo "TEST #37"
	$(SCAM) -r task4.scm testcase/task4.3 > result 
	diff result testcase/task4.3.expected
	@echo ""

test38: task4.scm testcase/task4.4
	@echo "TEST #38"
	$(SCAM) -r task4.scm testcase/task4.4 > result
	diff result testcase/task4.4.expected
	@echo ""

test39: task4.scm testcase/task4.5
	@echo "TEST #39"
	$(SCAM) -r task4.scm testcase/task4.5 > result
	diff result testcase/task4.5.expected
	@echo ""

#test44: task4.scm testcase/task4.10
#	@echo "TEST #44"
#	$(SCAM) -r task4.scm testcase/task4.10 > result
#	diff result testcase/task4.10.expected
#	@echo ""

test45: task5.scm testcase/task5.0
	@echo "TEST #45"
	$(SCAM) -r task5.scm testcase/task5.0 > result
	diff result testcase/task5.0.expected
	@echo ""

test46: task5.scm testcase/task5.1
	@echo "TEST #46"
	$(SCAM) -r task5.scm testcase/task5.1 > result
	diff result testcase/task5.1.expected
	@echo ""

test47: task5.scm testcase/task5.2
	@echo "TEST #47"
	$(SCAM) -r task5.scm testcase/task5.2 > result
	diff result testcase/task5.2.expected
	@echo ""

test48: task5.scm testcase/task5.3
	@echo "TEST #48"
	$(SCAM) -r task5.scm testcase/task5.3 > result
	diff result testcase/task5.3.expected
	@echo ""

test49: task5.scm testcase/task5.4
	@echo "TEST #49"
	$(SCAM) -r task5.scm testcase/task5.4 > result
	diff result testcase/task5.4.expected
	@echo ""

test50: task5.scm testcase/task5.5
	@echo "TEST #50"
	$(SCAM) -r task5.scm testcase/task5.5 > result 
	diff result testcase/task5.5.expected
	@echo ""

test51: task5.scm testcase/task5.6
	@echo "TEST #51"
	$(SCAM) -r task5.scm testcase/task5.6 > result
	diff result testcase/task5.6.expected
	@echo ""

test52: task5.scm testcase/task5.7
	@echo "TEST #52"
	$(SCAM) -r task5.scm testcase/task5.7 > result
	diff result testcase/task5.7.expected
	@echo ""


#test55: task5.scm testcase/task5.10
#	@echo "TEST #55" 
#	$(SCAM) -r task5.scm testcase/task5.10 > result
#	diff result testcase/task5.10.expected
#	@echo ""

test56: task6.scm testcase/task6.0
	@echo "TEST #56"
	$(SCAM) -r task6.scm testcase/task6.0 > result
	diff result testcase/task6.0.expected
	@echo ""

test57: task6.scm testcase/task6.1
	@echo "TEST #57"
	$(SCAM) -r task6.scm testcase/task6.1 > result
	diff result testcase/task6.1.expected
	@echo ""

test58: task6.scm testcase/task6.2
	@echo "TEST #58"
	$(SCAM) -r task6.scm testcase/task6.2 > result
	diff result testcase/task6.2.expected
	@echo ""

test59: task6.scm testcase/task6.3
	@echo "TEST #59"
	$(SCAM) -r task6.scm testcase/task6.3 > result
	diff result testcase/task6.3.expected
	@echo ""

test60: task6.scm testcase/task6.4
	@echo "TEST #60"
	$(SCAM) -r task6.scm testcase/task6.4 > result
	diff result testcase/task6.4.expected
	@echo ""

test61: task6.scm testcase/task6.5
	@echo "TEST #61"
	$(SCAM) -r task6.scm testcase/task6.5 > result
	diff result testcase/task6.5.expected
	@echo ""

test62: task6.scm testcase/task6.6
	@echo "TEST #62"
	$(SCAM) -r task6.scm testcase/task6.6 > result
	diff result testcase/task6.6.expected
	@echo ""

test63: task6.scm testcase/task6.7
	@echo "TEST #63"
	$(SCAM) -r task6.scm testcase/task6.7 > result
	diff result testcase/task6.7.expected
	@echo ""

test64: task6.scm testcase/task6.8
	@echo "TEST #64"
	$(SCAM) -r task6.scm testcase/task6.8 > result
	diff result testcase/task6.8.expected
	@echo ""

test65: task6.scm testcase/task6.9
	@echo "TEST #65"
	$(SCAM) -r task6.scm testcase/task6.9 > result
	diff result testcase/task6.9.expected
	@echo ""

#test66: task6.scm testcase/task6.10
#	@echo "TEST #66"
#	$(SCAM) -r task6.scm testcase/task6.10 > result
#	diff result testcase/task6.10.expected
#	@echo ""

test67: task7.scm testcase/task7.0
	@echo "TEST #67"
	$(SCAM) -r task7.scm testcase/task7.0 > result
	diff result testcase/task7.0.expected
	@echo ""

test68: task7.scm testcase/task7.1
	@echo "TEST #68" 
	$(SCAM) -r task7.scm testcase/task7.1 > result
	diff result testcase/task7.1.expected
	@echo "" 

test69: task7.scm testcase/task7.2
	@echo "TEST #69"
	$(SCAM) -r task7.scm testcase/task7.2 > result
	diff result testcase/task7.2.expected
	@echo ""

test70: task7.scm testcase/task7.3
	@echo "TEST #70"
	$(SCAM) -r task7.scm testcase/task7.3 > result
	diff result testcase/task7.3.expected
	@echo ""

test71: task7.scm testcase/task7.4
	@echo "TEST #71"
	$(SCAM) -r task7.scm testcase/task7.4 > result
	diff result testcase/task7.4.expected
	@echo ""

test72: task7.scm testcase/task7.5
	@echo "TEST #72"
	$(SCAM) -r task7.scm testcase/task7.5 > result
	diff result testcase/task7.5.expected
	@echo ""

test73: task7.scm testcase/task7.6
	@echo "TEST #73"
	$(SCAM) -r task7.scm testcase/task7.6 > result
	diff result testcase/task7.6.expected
	@echo ""

test74: task7.scm testcase/task7.7
	@echo "TEST #74"
	$(SCAM) -r task7.scm testcase/task7.7 > result
	diff result testcase/task7.7.expected
	@echo ""

test75: task7.scm testcase/task7.8
	@echo "TEST #75"
	$(SCAM) -r task7.scm testcase/task7.8 > result
	diff result testcase/task7.8.expected
	@echo "" 

test76: task7.scm testcase/task7.9
	@echo "TEST #76"
	$(SCAM) -r task7.scm testcase/task7.9 > result
	diff result testcase/task7.9.expected
	@echo ""

#test77: task7.scm testcase/task7.10
#	@echo "TEST #77"
#	$(SCAM) -r task7.scm testcase/task7.10 > result
#	diff result testcase/task7.10.expected
#	@echo ""

test78: task8.scm testcase/task8.0
	@echo "TEST #78"
	$(SCAM) -r task8.scm testcase/task8.0 > result
	diff result testcase/task8.0.expected
	@echo ""

#test79: task8.scm testcase/task8.0
#	@echo "TEST #79"
#	$(SCAM) -r task8.scm testcase/task8.0 > result
#	diff result testcase/task8.0.expected
#	@echo ""

test80: task8.scm testcase/task8.1
	@echo "TEST #80"
	$(SCAM) -r task8.scm testcase/task8.1 > result
	diff result testcase/task8.1.expected
	@echo ""

test81: task8.scm testcase/task8.1
	@echo "TEST #81"
	$(SCAM) -r task8.scm testcase/task8.1 > result
	diff result testcase/task8.1.expected
	@echo ""

test82: task8.scm testcase/task8.2
	@echo "TEST #82"
	$(SCAM) -r task8.scm testcase/task8.2 > result
	diff result testcase/task8.2.expected
	@echo ""

test83: task8.scm testcase/task8.2
	@echo "TEST #83"
	$(SCAM) -r task8.scm testcase/task8.2 > result
	diff result testcase/task8.2.expected
	@echo ""

test84: task8.scm testcase/task8.3
	@echo "TEST #84"
	$(SCAM) -r task8.scm testcase/task8.3 > result
	diff result testcase/task8.3.expected
	@echo ""

test85: task8.scm testcase/task8.3
	@echo "TEST #85"
	$(SCAM) -r task8.scm testcase/task8.3 > result
	diff result testcase/task8.3.expected
	@echo ""

test86: task8.scm testcase/task8.4
	@echo "TEST #86"
	$(SCAM) -r task8.scm testcase/task8.4 > result
	diff result testcase/task8.4.expected
	@echo ""

test87: task8.scm testcase/task8.4
	@echo "TEST #87"
	$(SCAM) -r task8.scm testcase/task8.4 > result
	diff result testcase/task8.4.expected
	@echo ""

test88: task8.scm testcase/task8.5
	@echo "TEST #88"
	$(SCAM) -r task8.scm testcase/task8.5 > result
	diff result testcase/task8.5.expected
	@echo ""

test89: task8.scm testcase/task8.5
	@echo "TEST #89"
	$(SCAM) -r task8.scm testcase/task8.5 > result
	diff result testcase/task8.5.expected
	@echo ""
test90: task8.scm testcase/task8.6
	@echo "TEST #89"
	$(SCAM) -r task8.scm testcase/task8.6 > result
	diff result testcase/task8.6.expected
	@echo ""
test91: task8.scm testcase/task8.7
	@echo "TEST #89"
	$(SCAM) -r task8.scm testcase/task8.7 > result
	diff result testcase/task8.7.expected
	@echo ""
test92: task8.scm testcase/task8.8
	@echo "TEST #89"
	$(SCAM) -r task8.scm testcase/task8.8 > result
	diff result testcase/task8.8.expected
	@echo ""
test93: task8.scm testcase/task8.9
	@echo "TEST #89"
	$(SCAM) -r task8.scm testcase/task8.9 > result
	diff result testcase/task8.9.expected
	@echo ""
