all: task1\
	task2\
	task3\
	task4\
	task5\
	task6\
	task7\
	task8\
	
author: author.scm
	scam -r author.scm
task1: task1.scm
	scam -r task1.scm  task1.args
task2: task2.scm
	scam -r task2.scm task2.args
task3: task3.scm
	scam -r task3.scm task3.args	
task4: task4.scm
	scam -r task4.scm task4.args
task5: task5.scm
	scam -r task5.scm task5.args
task6: task6.scm
	scam -r task6.scm task6.args
task7: task7.scm
	scam -r task7.scm task7.args
task8: task8.scm
	scam -r task8.scm task8.args
