author: author.scm
	scam -r author.scm
task1: task1.scm
	scam -r task1.scm  task1.args
task2: task2.scm
	scam -r task2.scm task2.args
task3: task3.scm
	scam -r task3.scm task3.args	
task4: task4.scm
	scam -r task4.scm task4.args
