(define (node value left right)
    (define (display) (print value))
    this
)
(define (newBST value)
	(node value nil nil)
)
(define (displayBST root)
        (define (iter root indent)
            (if (valid? root)
                (begin
                    (iter (root 'right) (string+ indent "    "))
                    (print indent)
                    ((root 'display))
                    (println)
                    (iter (root 'left) (string+ indent "    "))
                    )
                )
            )
        (iter root "")
        )
(define (insertBST Tree item)
    (cond
        ; If Tree is empty make a root
        ((null? Tree) (node item '() '()))
        ; Else if the value is the same return the tree
        ((= item (Tree 'value)) Tree)
        ; If less than, make a new Tree and recur left
        ((< item (Tree 'value))
            (node (Tree 'value)
                    (insertBST (Tree 'left) item)
                    (Tree 'right)
            )
        )
        ; If less than, make a new Tree and recur right
        ((> item (Tree 'value))
            (node (Tree 'value)
                        (Tree 'left)
                        (insertBST (Tree 'right) item)
            )
        )
    )
)
(define (main)
;	(define t0 (newBST 5))
;	(define t1 (insertBST t0 2))
;	(define t2 (insertBST t1 8))
;	(displayBST t2)
 (setPort (open (getElement ScamArgs 1) 'read))
        (define env this)
    (define (iter expr)
         (if (not (eof?)) (begin (eval expr env) (iter (readExpr))))
         )
    (iter (readExpr))

)

