all: 
	scam -r author.scm
task1:
	echo "52" > task1.args
	scam -r task1.scm task1.args
task2:
	echo "100 0.79 0.79" > task2.args
	scam -r task2.scm task2.args

task3:
	echo "2 144" > task3.args	
	scam -r task3.scm task3.args

task4:
	echo "1 1 5" > task4.args
	scam -r task4.scm task4.args
task5:
	echo "(define (f a b c d) (+ a b c d ))" > task5.args
	echo "1 2 3 4" >> task5.args
	scam -r task5.scm task5.args

task6:
	echo "(lambda (x) (/ (if (= (% x 2) 0) 1 -1) (+ x 1.0)))" > task6.args
	echo "1193" >> task6.args 
	scam -r task6.scm task6.args

task7:
	echo "12727 11080" > task7.args
	scam -r task7.scm task7.args

task8i:
	echo "2" > task8.args
	scam -r task8i.scm task8.args
task8r:
	echo "1" > task8.args
	scam -r task8r.scm task8.args
task9r:
	echo "0" > task9r.args
	scam -r task9r.scm task9r.args
task9i:
	echo "0" > task9i.args
	scam -r task9i.scm task9i.args
