SCAM=scam   # fill in your absolute path

testall: test1 test2 \
	test3 \
	test4 \
	test5 \
	test6 \
	test7 \
	test8 \
	test9 \
	test10 \
	test11 \
	test12 \
	test13 \
	test14 \
	test15 \
	test16 \
	test17 \
	test18 \
	test19 \
	test20 \
	test21 \
	test22 \
	test23 \
	test24 \
	test25 \
	test26 \
	test27 \
	test28 \
	test29 \
	test30 \
	test31 \
	test32 \
	test33 \
	test34 \
	test35 \
	test36 \
	test37 \
	test38 \
	test39 \
	test40 \
	test41 \
	test42 \
	test43 \
	test44 \
	test45 \
	test46 \
	test47 \
	test48 \
	test49 \
	test50 \
	test51 \
	test52 \
	test53 \
	test54 \
	test55 \
	test56 \
	test57 \
	test58 \
	test59 \
	test60 \
	test61 \
	test62 \
	test63 \
	test64 \
	test65 \
	test66 \
	test67 \
	test68 \
	test69 \
	test70 \
	test71 \
	test72 \
	test73 \
	test74 \
	test75 \
	test76 \
	test77 \
	test78 \
	test79 \
	test80 \
	test81 \
	test82 \
	test83 \
	test84 \
	test85 \
	test86 \
	test87 \
	test88 \
	test89 \
	test90 \
	test91 \
	test92 \
	test93 \
	test94 \
	test95 \
	test96 \
	test97 \
	test98 \
	test99 \
	test100 \
	test101 \
	test102 \
	test103 \
	test104 \
	test105 \
	test106 \
	test107 \
	test108 \
	test109 \
	test110 \
	test111


test1: task1.scm testcase_resubmit/task1.0
	@echo "TEST #1"
	$(SCAM) -r task1.scm testcase_resubmit/task1.0 > result
	diff result testcase_resubmit/task1.0.expected
	@echo ""

test2: task1.scm testcase_resubmit/task1.1
	@echo "TEST #2"
	$(SCAM) -r task1.scm testcase_resubmit/task1.1 >result
	diff result testcase_resubmit/task1.1.expected
	@echo ""

test3: task1.scm testcase_resubmit/task1.2
	@echo "TEST #3"
	$(SCAM) -r task1.scm testcase_resubmit/task1.2 > result
	diff result testcase_resubmit/task1.2.expected
	@echo ""

test4: task1.scm testcase_resubmit/task1.3
	@echo "TEST #4"
	$(SCAM) -r task1.scm testcase_resubmit/task1.3 > result
	diff result testcase_resubmit/task1.3.expected
	@echo ""

test5: task1.scm testcase_resubmit/task1.4
	@echo "TEST #5"
	$(SCAM) -r task1.scm testcase_resubmit/task1.4 > result
	diff result testcase_resubmit/task1.4.expected
	@echo ""

test6: task1.scm testcase_resubmit/task1.5
	@echo "TEST #6"
	$(SCAM) -r task1.scm testcase_resubmit/task1.5 > result
	diff result testcase_resubmit/task1.5.expected
	@echo ""

test7: task1.scm testcase_resubmit/task1.6
	@echo "TEST #7"
	$(SCAM) -r task1.scm testcase_resubmit/task1.6 > result
	diff result testcase_resubmit/task1.6.expected
	@echo ""

test8: task1.scm testcase_resubmit/task1.7
	@echo "TEST #8"
	$(SCAM) -r task1.scm testcase_resubmit/task1.7 >result
	diff result testcase_resubmit/task1.7.expected
	@echo ""

test9: task1.scm testcase_resubmit/task1.8
	@echo "TEST #9"
	$(SCAM) -r task1.scm testcase_resubmit/task1.8 > result
	diff result testcase_resubmit/task1.8.expected
	@echo ""

test10: task1.scm testcase_resubmit/task1.9
	@echo "TEST #10"
	$(SCAM) -r task1.scm testcase_resubmit/task1.9 > result
	diff result testcase_resubmit/task1.9.expected
	@echo ""

test11: task1.scm testcase_resubmit/task1.10
	@echo "TEST #11"
	$(SCAM) -r task1.scm testcase_resubmit/task1.10 > result
	diff result testcase_resubmit/task1.10.expected
	@echo ""

test12: task2.scm testcase_resubmit/task2.0
	@echo "TEST #12"
	$(SCAM) -r task2.scm testcase_resubmit/task2.0 > result
	diff result testcase_resubmit/task2.0.expected
	@echo ""

test13: task2.scm testcase_resubmit/task2.1
	@echo "TEST #13"
	$(SCAM) -r task2.scm testcase_resubmit/task2.1 > result
	diff result testcase_resubmit/task2.1.expected
	@echo ""

test14: task2.scm testcase_resubmit/task2.2
	@echo "TEST #14"
	$(SCAM) -r task2.scm testcase_resubmit/task2.2 > result
	diff result testcase_resubmit/task2.2.expected
	@echo ""

test15: task2.scm testcase_resubmit/task2.3
	@echo "TEST #15"
	$(SCAM) -r task2.scm testcase_resubmit/task2.3 > result
	diff result testcase_resubmit/task2.3.expected
	@echo ""

test16: task2.scm testcase_resubmit/task2.4
	@echo "TEST #16"
	$(SCAM) -r task2.scm testcase_resubmit/task2.4 > result
	diff result testcase_resubmit/task2.4.expected
	@echo ""

test17: task2.scm testcase_resubmit/task2.5
	@echo "TEST #17"
	$(SCAM) -r task2.scm testcase_resubmit/task2.5 > result
	diff result testcase_resubmit/task2.5.expected
	@echo ""

test18: task2.scm testcase_resubmit/task2.6
	@echo "TEST #18"
	$(SCAM) -r task2.scm testcase_resubmit/task2.6 > result
	diff result testcase_resubmit/task2.6.expected
	@echo ""

test19: task2.scm testcase_resubmit/task2.7
	@echo "TEST #19"
	$(SCAM) -r task2.scm testcase_resubmit/task2.7 > result
	diff result testcase_resubmit/task2.7.expected
	@echo ""

test20: task2.scm testcase_resubmit/task2.8
	@echo "TEST #20"
	$(SCAM) -r task2.scm testcase_resubmit/task2.8 > result
	diff result testcase_resubmit/task2.8.expected
	@echo ""

test21: task2.scm testcase_resubmit/task2.9
	@echo "TEST #21"
	$(SCAM) -r task2.scm testcase_resubmit/task2.9 > result
	diff result testcase_resubmit/task2.9.expected
	@echo ""

test22: task2.scm testcase_resubmit/task2.10
	@echo "TEST #22"
	$(SCAM) -r task2.scm testcase_resubmit/task2.10 > result
	diff result testcase_resubmit/task2.10.expected
	@echo ""

test23: task3.scm testcase_resubmit/task3.0
	@echo "TEST #23"
	$(SCAM) -r task3.scm testcase_resubmit/task3.0 > result
	diff result testcase_resubmit/task3.0.expected
	@echo ""

test24: task3.scm testcase_resubmit/task3.1
	@echo "TEST #24"
	$(SCAM) -r task3.scm testcase_resubmit/task3.1 > result
	diff result testcase_resubmit/task3.1.expected
	@echo ""

test25: task3.scm testcase_resubmit/task3.2
	@echo "TEST #25"
	$(SCAM) -r task3.scm testcase_resubmit/task3.2 > result
	diff result testcase_resubmit/task3.2.expected
	@echo ""

test26: task3.scm testcase_resubmit/task3.3
	@echo "TEST #26"
	$(SCAM) -r task3.scm testcase_resubmit/task3.3 > result
	diff result testcase_resubmit/task3.3.expected
	@echo ""

test27: task3.scm testcase_resubmit/task3.4
	@echo "TEST #27"
	$(SCAM) -r task3.scm testcase_resubmit/task3.4 > result
	diff result testcase_resubmit/task3.4.expected
	@echo ""

test28: task3.scm testcase_resubmit/task3.5
	@echo "TEST #28"
	$(SCAM) -r task3.scm testcase_resubmit/task3.5 > result
	diff result testcase_resubmit/task3.5.expected
	@echo ""

test29: task3.scm testcase_resubmit/task3.6
	@echo "TEST #29"
	$(SCAM) -r task3.scm testcase_resubmit/task3.6 > result
	diff result testcase_resubmit/task3.6.expected
	@echo ""

test30: task3.scm testcase_resubmit/task3.7
	@echo "TEST #30"
	$(SCAM) -r task3.scm testcase_resubmit/task3.7 > result
	diff result testcase_resubmit/task3.7.expected
	@echo ""

test31: task3.scm testcase_resubmit/task3.8
	@echo "TEST #31"
	$(SCAM) -r task3.scm testcase_resubmit/task3.8 > result
	diff result testcase_resubmit/task3.8.expected
	@echo ""

test32: task3.scm testcase_resubmit/task3.9
	@echo "TEST #32"
	$(SCAM) -r task3.scm testcase_resubmit/task3.9 > result
	diff result testcase_resubmit/task3.9.expected
	@echo ""

test33: task3.scm testcase_resubmit/task3.10
	@echo "TEST #33"
	$(SCAM) -r task3.scm testcase_resubmit/task3.10 > result
	diff result testcase_resubmit/task3.10.expected
	@echo ""

test34: task4.scm testcase_resubmit/task4.0
	@echo "TEST #34"
	$(SCAM) -r task4.scm testcase_resubmit/task4.0 > result
	diff result testcase_resubmit/task4.0.expected
	@echo ""

test35: task4.scm testcase_resubmit/task4.1
	@echo "TEST #35"
	$(SCAM) -r task4.scm testcase_resubmit/task4.1 > result 
	diff result testcase_resubmit/task4.1.expected
	@echo ""

test36: task4.scm testcase_resubmit/task4.2
	@echo "TEST #36"
	$(SCAM) -r task4.scm testcase_resubmit/task4.2 > result
	diff result testcase_resubmit/task4.2.expected
	@echo ""

test37: task4.scm testcase_resubmit/task4.3
	@echo "TEST #37"
	$(SCAM) -r task4.scm testcase_resubmit/task4.3 > result 
	diff result testcase_resubmit/task4.3.expected
	@echo ""

test38: task4.scm testcase_resubmit/task4.4
	@echo "TEST #38"
	$(SCAM) -r task4.scm testcase_resubmit/task4.4 > result
	diff result testcase_resubmit/task4.4.expected
	@echo ""

test39: task4.scm testcase_resubmit/task4.5
	@echo "TEST #39"
	$(SCAM) -r task4.scm testcase_resubmit/task4.5 > result
	diff result testcase_resubmit/task4.5.expected
	@echo ""

test40: task4.scm testcase_resubmit/task4.6
	@echo "TEST #40"
	$(SCAM) -r task4.scm testcase_resubmit/task4.6 > result
	diff result testcase_resubmit/task4.6.expected
	@echo ""

test41: task4.scm testcase_resubmit/task4.7
	@echo "TEST #41"
	$(SCAM) -r task4.scm testcase_resubmit/task4.7 > result
	diff result testcase_resubmit/task4.7.expected
	@echo ""

test42: task4.scm testcase_resubmit/task4.8
	@echo "TEST #42"
	$(SCAM) -r task4.scm testcase_resubmit/task4.8 > result
	diff result testcase_resubmit/task4.8.expected
	@echo ""

test43: task4.scm testcase_resubmit/task4.9
	@echo "TEST #43"
	$(SCAM) -r task4.scm testcase_resubmit/task4.9 > result
	diff result testcase_resubmit/task4.9.expected
	@echo ""

test44: task4.scm testcase_resubmit/task4.10
	@echo "TEST #44"
	$(SCAM) -r task4.scm testcase_resubmit/task4.10 > result
	diff result testcase_resubmit/task4.10.expected
	@echo ""

test45: task5.scm testcase_resubmit/task5.0
	@echo "TEST #45"
	$(SCAM) -r task5.scm testcase_resubmit/task5.0 > result
	diff result testcase_resubmit/task5.0.expected
	@echo ""

test46: task5.scm testcase_resubmit/task5.1
	@echo "TEST #46"
	$(SCAM) -r task5.scm testcase_resubmit/task5.1 > result
	diff result testcase_resubmit/task5.1.expected
	@echo ""

test47: task5.scm testcase_resubmit/task5.2
	@echo "TEST #47"
	$(SCAM) -r task5.scm testcase_resubmit/task5.2 > result
	diff result testcase_resubmit/task5.2.expected
	@echo ""

test48: task5.scm testcase_resubmit/task5.3
	@echo "TEST #48"
	$(SCAM) -r task5.scm testcase_resubmit/task5.3 > result
	diff result testcase_resubmit/task5.3.expected
	@echo ""

test49: task5.scm testcase_resubmit/task5.4
	@echo "TEST #49"
	$(SCAM) -r task5.scm testcase_resubmit/task5.4 > result
	diff result testcase_resubmit/task5.4.expected
	@echo ""

test50: task5.scm testcase_resubmit/task5.5
	@echo "TEST #50"
	$(SCAM) -r task5.scm testcase_resubmit/task5.5 > result 
	diff result testcase_resubmit/task5.5.expected
	@echo ""

test51: task5.scm testcase_resubmit/task5.6
	@echo "TEST #51"
	$(SCAM) -r task5.scm testcase_resubmit/task5.6 > result
	diff result testcase_resubmit/task5.6.expected
	@echo ""

test52: task5.scm testcase_resubmit/task5.7
	@echo "TEST #52"
	$(SCAM) -r task5.scm testcase_resubmit/task5.7 > result
	diff result testcase_resubmit/task5.7.expected
	@echo ""

test53: task5.scm testcase_resubmit/task5.8
	@echo "TEST #53"
	$(SCAM) -r task5.scm testcase_resubmit/task5.8 > result
	diff result testcase_resubmit/task5.8.expected
	@echo ""

test54: task5.scm testcase_resubmit/task5.9
	@echo "TEST #54"
	$(SCAM) -r task5.scm testcase_resubmit/task5.9 > result
	diff result testcase_resubmit/task5.9.expected
	@echo ""

test55: task5.scm testcase_resubmit/task5.10
	@echo "TEST #55" 
	$(SCAM) -r task5.scm testcase_resubmit/task5.10 > result
	diff result testcase_resubmit/task5.10.expected
	@echo ""

test56: task6.scm testcase_resubmit/task6.0
	@echo "TEST #56"
	$(SCAM) -r task6.scm testcase_resubmit/task6.0 > result
	diff result testcase_resubmit/task6.0.expected
	@echo ""

test57: task6.scm testcase_resubmit/task6.1
	@echo "TEST #57"
	$(SCAM) -r task6.scm testcase_resubmit/task6.1 > result
	diff result testcase_resubmit/task6.1.expected
	@echo ""

test58: task6.scm testcase_resubmit/task6.2
	@echo "TEST #58"
	$(SCAM) -r task6.scm testcase_resubmit/task6.2 > result
	diff result testcase_resubmit/task6.2.expected
	@echo ""

test59: task6.scm testcase_resubmit/task6.3
	@echo "TEST #59"
	$(SCAM) -r task6.scm testcase_resubmit/task6.3 > result
	diff result testcase_resubmit/task6.3.expected
	@echo ""

test60: task6.scm testcase_resubmit/task6.4
	@echo "TEST #60"
	$(SCAM) -r task6.scm testcase_resubmit/task6.4 > result
	diff result testcase_resubmit/task6.4.expected
	@echo ""

test61: task6.scm testcase_resubmit/task6.5
	@echo "TEST #61"
	$(SCAM) -r task6.scm testcase_resubmit/task6.5 > result
	diff result testcase_resubmit/task6.5.expected
	@echo ""

test62: task6.scm testcase_resubmit/task6.6
	@echo "TEST #62"
	$(SCAM) -r task6.scm testcase_resubmit/task6.6 > result
	diff result testcase_resubmit/task6.6.expected
	@echo ""

test63: task6.scm testcase_resubmit/task6.7
	@echo "TEST #63"
	$(SCAM) -r task6.scm testcase_resubmit/task6.7 > result
	diff result testcase_resubmit/task6.7.expected
	@echo ""

test64: task6.scm testcase_resubmit/task6.8
	@echo "TEST #64"
	$(SCAM) -r task6.scm testcase_resubmit/task6.8 > result
	diff result testcase_resubmit/task6.8.expected
	@echo ""

test65: task6.scm testcase_resubmit/task6.9
	@echo "TEST #65"
	$(SCAM) -r task6.scm testcase_resubmit/task6.9 > result
	diff result testcase_resubmit/task6.9.expected
	@echo ""

test66: task6.scm testcase_resubmit/task6.10
	@echo "TEST #66"
	$(SCAM) -r task6.scm testcase_resubmit/task6.10 > result
	diff result testcase_resubmit/task6.10.expected
	@echo ""

test67: task7.scm testcase_resubmit/task7.0
	@echo "TEST #67"
	$(SCAM) -r task7.scm testcase_resubmit/task7.0 > result
	diff result testcase_resubmit/task7.0.expected
	@echo ""

test68: task7.scm testcase_resubmit/task7.1
	@echo "TEST #68" 
	$(SCAM) -r task7.scm testcase_resubmit/task7.1 > result
	diff result testcase_resubmit/task7.1.expected
	@echo "" 

test69: task7.scm testcase_resubmit/task7.2
	@echo "TEST #69"
	$(SCAM) -r task7.scm testcase_resubmit/task7.2 > result
	diff result testcase_resubmit/task7.2.expected
	@echo ""

test70: task7.scm testcase_resubmit/task7.3
	@echo "TEST #70"
	$(SCAM) -r task7.scm testcase_resubmit/task7.3 > result
	diff result testcase_resubmit/task7.3.expected
	@echo ""

test71: task7.scm testcase_resubmit/task7.4
	@echo "TEST #71"
	$(SCAM) -r task7.scm testcase_resubmit/task7.4 > result
	diff result testcase_resubmit/task7.4.expected
	@echo ""

test72: task7.scm testcase_resubmit/task7.5
	@echo "TEST #72"
	$(SCAM) -r task7.scm testcase_resubmit/task7.5 > result
	diff result testcase_resubmit/task7.5.expected
	@echo ""

test73: task7.scm testcase_resubmit/task7.6
	@echo "TEST #73"
	$(SCAM) -r task7.scm testcase_resubmit/task7.6 > result
	diff result testcase_resubmit/task7.6.expected
	@echo ""

test74: task7.scm testcase_resubmit/task7.7
	@echo "TEST #74"
	$(SCAM) -r task7.scm testcase_resubmit/task7.7 > result
	diff result testcase_resubmit/task7.7.expected
	@echo ""

test75: task7.scm testcase_resubmit/task7.8
	@echo "TEST #75"
	$(SCAM) -r task7.scm testcase_resubmit/task7.8 > result
	diff result testcase_resubmit/task7.8.expected
	@echo "" 

test76: task7.scm testcase_resubmit/task7.9
	@echo "TEST #76"
	$(SCAM) -r task7.scm testcase_resubmit/task7.9 > result
	diff result testcase_resubmit/task7.9.expected
	@echo ""

test77: task7.scm testcase_resubmit/task7.10
	@echo "TEST #77"
	$(SCAM) -r task7.scm testcase_resubmit/task7.10 > result
	diff result testcase_resubmit/task7.10.expected
	@echo ""

test78: task8i.scm testcase_resubmit/task8.0
	@echo "TEST #78"
	$(SCAM) -r task8i.scm testcase_resubmit/task8.0 > result
	diff result testcase_resubmit/task8i.0.expected
	@echo ""

test79: task8r.scm testcase_resubmit/task8.0
	@echo "TEST #79"
	$(SCAM) -r task8r.scm testcase_resubmit/task8.0 > result
	diff result testcase_resubmit/task8r.0.expected
	@echo ""

test80: task8i.scm testcase_resubmit/task8.1
	@echo "TEST #80"
	$(SCAM) -r task8i.scm testcase_resubmit/task8.1 > result
	diff result testcase_resubmit/task8i.1.expected
	@echo ""

test81: task8r.scm testcase_resubmit/task8.1
	@echo "TEST #81"
	$(SCAM) -r task8r.scm testcase_resubmit/task8.1 > result
	diff result testcase_resubmit/task8r.1.expected
	@echo ""

test82: task8i.scm testcase_resubmit/task8.2
	@echo "TEST #82"
	$(SCAM) -r task8i.scm testcase_resubmit/task8.2 > result
	diff result testcase_resubmit/task8i.2.expected
	@echo ""

test83: task8r.scm testcase_resubmit/task8.2
	@echo "TEST #83"
	$(SCAM) -r task8r.scm testcase_resubmit/task8.2 > result
	diff result testcase_resubmit/task8r.2.expected
	@echo ""

test84: task8i.scm testcase_resubmit/task8.3
	@echo "TEST #84"
	$(SCAM) -r task8i.scm testcase_resubmit/task8.3 > result
	diff result testcase_resubmit/task8i.3.expected
	@echo ""

test85: task8r.scm testcase_resubmit/task8.3
	@echo "TEST #85"
	$(SCAM) -r task8r.scm testcase_resubmit/task8.3 > result
	diff result testcase_resubmit/task8r.3.expected
	@echo ""

test86: task8i.scm testcase_resubmit/task8.4
	@echo "TEST #86"
	$(SCAM) -r task8i.scm testcase_resubmit/task8.4 > result
	diff result testcase_resubmit/task8i.4.expected
	@echo ""

test87: task8r.scm testcase_resubmit/task8.4
	@echo "TEST #87"
	$(SCAM) -r task8r.scm testcase_resubmit/task8.4 > result
	diff result testcase_resubmit/task8r.4.expected
	@echo ""

test88: task8i.scm testcase_resubmit/task8.5
	@echo "TEST #88"
	$(SCAM) -r task8i.scm testcase_resubmit/task8.5 > result
	diff result testcase_resubmit/task8i.5.expected
	@echo ""

test89: task8r.scm testcase_resubmit/task8.5
	@echo "TEST #89"
	$(SCAM) -r task8r.scm testcase_resubmit/task8.5 > result
	diff result testcase_resubmit/task8r.5.expected
	@echo ""

test90: task9i.scm testcase_resubmit/task9.0
	@echo "TEST #90"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.0 > result
	diff result testcase_resubmit/task9i.0.expected
	@echo ""

test91: task9r.scm testcase_resubmit/task9.0
	@echo "TEST #91"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.0 > result
	diff result testcase_resubmit/task9r.0.expected
	@echo ""

test92: task9i.scm testcase_resubmit/task9.1
	@echo "TEST #92"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.1 > result
	diff result testcase_resubmit/task9i.1.expected
	@echo ""

test93: task9r.scm testcase_resubmit/task9.1
	@echo "TEST #93"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.1 > result
	diff result testcase_resubmit/task9r.1.expected
	@echo ""

test94: task9i.scm testcase_resubmit/task9.2
	@echo "TEST #94"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.2 > result
	diff result testcase_resubmit/task9i.2.expected
	@echo ""

test95: task9r.scm testcase_resubmit/task9.2
	@echo "TEST #95"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.2 > result
	diff result testcase_resubmit/task9r.2.expected
	@echo ""

test96: task9i.scm testcase_resubmit/task9.3
	@echo "TEST #96"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.3 > result
	diff result testcase_resubmit/task9i.3.expected
	@echo ""

test97: task9r.scm testcase_resubmit/task9.3
	@echo "TEST #97"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.3 > result
	diff result testcase_resubmit/task9r.3.expected
	@echo ""

test98: task9i.scm testcase_resubmit/task9.4
	@echo "TEST #98"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.4 > result
	diff result testcase_resubmit/task9i.4.expected
	@echo ""

test99: task9r.scm testcase_resubmit/task9.4
	@echo "TEST #99"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.4 > result
	diff result testcase_resubmit/task9r.4.expected
	@echo ""

test100: task9i.scm testcase_resubmit/task9.5
	@echo "TEST #100"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.5 > result
	diff result testcase_resubmit/task9i.5.expected
	@echo ""

test101: task9r.scm testcase_resubmit/task9.5
	@echo "TEST #101"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.5 > result
	diff result testcase_resubmit/task9r.5.expected
	@echo ""

test102: task9i.scm testcase_resubmit/task9.6
	@echo "TEST #102"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.6 > result
	diff result testcase_resubmit/task9i.6.expected
	@echo ""

test103: task9r.scm testcase_resubmit/task9.6
	@echo "TEST #103"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.6 > result
	diff result testcase_resubmit/task9r.6.expected
	@echo ""

test104: task9i.scm testcase_resubmit/task9.7
	@echo "TEST #104"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.7 > result
	diff result testcase_resubmit/task9i.7.expected
	@echo "" 

test105: task9r.scm testcase_resubmit/task9.7
	@echo "TEST #105"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.7 > result
	diff result testcase_resubmit/task9r.7.expected
	@echo ""

test106: task9i.scm testcase_resubmit/task9.8
	@echo "TEST #106"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.8 > result
	diff result testcase_resubmit/task9i.8.expected
	@echo ""

test107: task9r.scm testcase_resubmit/task9.8
	@echo "TEST #107"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.8 > result
	diff result testcase_resubmit/task9r.8.expected
	@echo ""

test108: task9i.scm testcase_resubmit/task9.9
	@echo "TEST #108"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.9 > result
	diff result testcase_resubmit/task9i.9.expected
	@echo ""

test109: task9r.scm testcase_resubmit/task9.9
	@echo "TEST #109"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.9 > result
	diff result testcase_resubmit/task9r.9.expected
	@echo ""

test110: task9i.scm testcase_resubmit/task9.10
	@echo "TEST #110"
	$(SCAM) -r task9i.scm testcase_resubmit/task9.10 > result
	diff result testcase_resubmit/task9i.10.expected
	@echo ""

test111: task9r.scm testcase_resubmit/task9.10
	@echo "TEST #111"
	$(SCAM) -r task9r.scm testcase_resubmit/task9.10 > result
	diff result testcase_resubmit/task9r.10.expected
	@echo ""
