all: 
	scam -r author.scm
task1:
	echo "100" > task1.args
	scam -r task1.scm task1.args
task2:
	scam -r task2.scm

task3:
	echo "2 144" > task3.args	
	scam -r task3.scm task3.args

task4:
	echo "2 4 20" > task4.args
	scam -r task4.scm task4.args
