(define (square n)
	(* n n)
)

(define (S f n)
	(define i 0 )
	(define sum 0.0)
	(while (<= i n)
		(set! sum (+ sum (f i)))	
		(set! i (+ i 1))
	)
	sum
)

(define (w f n)
	(define i 0)
	(define result 0.0)
	(define sum 0.0)
	(define a)
	(define b)
	(define c)
	(while (<= i n)
		(cond 
			((= i 0 )(set! result ( f i ) ))
			(else 
			(set! a (S f i))
			(set! b (S f (- i 1)))
			(set! c (S f (+ i 1)))
			(set! result (/(-(* c b) (square a)) (+(- c (* 2 a)) b)))
			)
		)
		(set! i (+ i 1))
	)
	result
)

(define (main)
	(setPort (open (getElement ScamArgs 1) 'read))
	(define arg (eval (readExpr) this))
	(define arg1 (eval (readExpr) this))
	
	;(inspect arg)
	;(inspect arg1)
	;(inspect (S arg arg1))
	;(inspect (W arg arg1))
	(println "(S " arg " " arg1 ") is " (fmt "%.15f" (S arg arg1)))
	(println "(w " arg " "arg1 ") is " (fmt "%.15f" (w arg arg1)))
)