(define r 0.0)
(define s 0.0)
(define n 0)
(define (mandelbrot threshold)  
    (define (testFunc x y)
    	(define (iter x y n)
   		(if (and ( > (+ (* r r ) (* s s)) 4 ) (< n  threshold))
		   ;if this always true diverge
       			(set! r (+( - (* r r ) (* s s) ) x))
		        (set! s (+ (* 2 r s) y))
			n
			(iter x y (+ n 1))
	 	)
		(println "loop")
   	 )
    )
)
(define (main)
    (inspect ((mandelbrot 100)3 9 ))
    (inspect (<(+(* r r) (* s s) ) 4))
)
