(define (pascal row col left right)
  (cond((< row col) #f)
    	;((or (= 0 col) (= row col)) 1)
		((= col 0) left)
		((= row col )right)
	(else (+ (pascal (- row 1) col left right)
		 (pascal(- row 1)(- col 1) left right )))))

(define (main)
  (inspect (pascal 6 5 2 4))
  )
