(define (quote? item)
	(if(eq? item 'quote) #t #f)
)

(define (replace func items)
    (define (check obj lst)
        (if (null? (cddr lst))
            (if (eq? (car lst) obj)
                (cadr lst)
                obj
            )
            (if (eq? (car lst) obj)
                (cadr lst)
                (check obj (cddr lst))
            )
        )
    )

    (define (iter stuff)
        (cond
            ((null? stuff) stuff)
            ((object? (car stuff)) stuff)
	    ((quote? (car stuff))
		(set-car! stuff (check (car stuff) items)))
	    ((pair? (car stuff))
                (iter (car stuff))
                (iter (cdr stuff)))
            (else
                (set-car! stuff (check (car stuff) items))
                (iter (cdr stuff))
                )
            )
    ) 

    (iter (get 'parameters func))
    (iter (cadr (get 'code func)))
)

(define (main)
    (define env this)
    (define (iter expr)
         (if (not (eof?)) (begin (eval expr env) (iter (readExpr))))
         )
    (setPort (open (getElement ScamArgs 1) 'read))
    (iter (readExpr))
)
